### ISSUE TITLE
Suggestions for better action keys

### ISSUE THREAD

**Issue by AlisterH** [lmotta/polygonclickmap#2]
This is google's translation of the wiki page:
```
D: Delete the last region.
U: Undo the last deletion.
F: Fills the holes within the region.
A: Remove all regions.
P: Polygonalizes the regions. * Creation of polygons.
H: Help
```
It seems counterintuitive to use D for delete, which is effectively "undo", and U for what is effectively "redo".  I realise technically this is slightly different to a conventional undo/redo, because there are two different stacks, but this might make more sense:
```
U: Undo (remove the last region added).
R: Redo (add back the last region deleted).
F: Fill the holes within the region.
D: Delete all regions.
P: Polygonize the regions.
H: Help.
```
Or if you want to make it easy to use all the action keys with your left hand on a Qwerty keyboard, perhaps something like this would work:
```
D: Delete the last region.
R: Redo (add back the last region deleted).
F: Fill the holes within the region.
C: Clear all regions.
W: Write polygons for each region.
H: Help.
```

**Comment by lmotta** [comment]
Thanks for think about the best use the keys.

Below are my reasons for choosing keys

D and U: The QGIS interface use 'Del' Key for delete a feature selected, for me, is intuitive use D Key for delete, likewise, QGIS use the Undo expression for back the last delete.

R: The D key already was used, and, in the API of QGIS and Qt, the 'Remove' expression is common.

P: Because of the plugin name, and also, this is a term used to convert raster to vector.
